project:
  type: website

website:
  title: "IS415_GAA"
  navbar:
    left:
      - text: "Hand-on Exercise"
        menu: 
          - text: "Hand-on Exercise 1"
            href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
          - text: "Hand-on Exercise 2"
            href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
      - text: "In-class Exercise"
        menu: 
          - text: "In-Class Exercise 2"
            href: "In-class_Ex/In-class_Ex02/In-class_Ex02.html"
          - text: "In-class Exercise 3"
            href: "In-class_Ex/In-class_Ex03/In-class_Ex03.html"
          - text: "In-class Exercise 4"
            href: "In-class_Ex/In-class_Ex04/In-class_Ex04.html"
          - text: "In-class Exercise 5"
            href: "In-class_Ex/In-class_Ex05/In-class_Ex05.html"
      - text: "Take Home Exercise"
        menu:
         - text: "Take Home Exercise 1"
        
    right:
      - href: index.qmd
        text: HOME
      - about.qmd

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual