---
title: "In-class Exercise 2: Data Wrangling with R"
execute:
  warning: false
date: "`r Sys.Date()`"
echo: false
---

# Getting Started

```{r}
pacman::p_load(tidyverse, sf, funModeling)
```

# Importing Geospatial Data

##The geoBoundaries data set

```{r}
geoNGA <- st_read("data/geospatial/",
               layer = "geoBoundaries-NGA-ADM2") %>%
  st_transform(crs = 26392)
```

## The NGA data set

```{r}
NGA <- st_read("data/geospatial/",
               layer = "nga_admbnda_adm2_osgof_20190417") %>%
  st_transform(crs = 26392)
```

# Importing Aspatial Data

```{r}
NG <- st_read("data/geospatial",
              layer = "nga_admbnda_adm2_osgof_20190417") %>%
  st_transform(crs = 26392)
```

# Importing Aspatial Data

```{r}
wp_nga <- read_csv("data/aspatial/WPdx.csv") %>%
  filter(`#clean_country_name` == "Nigeria")
```

## Write the extracted data into rds format

# Converting Aspatial Data into Geospatial

# Converting Aspatial Data into Geospatial

```{r}
wp_nga$Geometry = st_as_sfc(wp_nga$`New Georeferenced Column`)
wp_nga
```

```{r}
wp_sf <- st_sf(wp_nga, crs=4326)
  wp_sf
```

# Projection transformation

# Projection transformation

```{r}
wp_sf <- wp_sf %>%
  st_transform(crs = 26392)
```
