---
title: "In Class Exercise 4: 2nd Order Spatial Point Patterns Analysis Methods"
execute:
  warning: false
date: "`r Sys.Date()`"
echo: false
---

# Loading the Packages

```{r}
pacman::p_load(maptools, sf, raster, spatstat, tmap)
```

# Importing the Data

```{r}
childcare_sf <- st_read("data/child-care-services-geojson.geojson") %>%
  st_transform(crs = 3414)
```

```{r}
sg_sf <- st_read(dsn = "data", 
                 layer="CostalOutline")
```

```{r}
mpsz_sf <- st_read(dsn = "data", 
                layer = "MP14_SUBZONE_WEB_PL")
```

# Mapping the geospatial data sets

```{r}
tmap_mode('view')
```

## Data Wrangling

```{r}
childcare <- as_Spatial(childcare_sf)
mpsz <- as_Spatial(mpsz_sf)
sg <- as_Spatial(sg_sf)
```

```{r}
childcare_sp <- as(childcare, "SpatialPoints")
sg_sp <- as(sg, "SpatialPolygons")
```

```{r}
childcare_ppp <- as(childcare_sp, "ppp")
childcare_ppp
```

### Duplicated Point Events

```{r}
childcare_ppp_jit <- rjitter(childcare_ppp, 
                             retry=TRUE, 
                             nsim=1, 
                             drop=TRUE)
```

```{r}
any(duplicated(childcare_ppp_jit))
```
## Creating Owin object

```{r}
sg_owin <- as(sg_sp, "owin")
plot(sg_owin)
```
## Combining point events object and owin object

```{r}
childcareSG_ppp = childcare_ppp[sg_owin]
summary(childcareSG_ppp)
```
```{r}
plot(childcareSG_ppp)
```